name: dockerHDDM CI

on:
  push:
    branches: [ "hddm1.0.1" ]

jobs:

  buildx:

    runs-on: ubuntu-latest
    env:
      HDDM_VERSION: hddm:1.0.1
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: push amd64
      run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.HDDM_VERSION}}-amd64 -f Dockerfile . --push
    - name: push arm64
      run: docker buildx build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.HDDM_VERSION}}-arm64 -f Dockerfile . --push
    - name: Build the Combined Manifest
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{env.HDDM_VERSION}} -f Dockerfile . --push
    - name: Build the Newest Manifest
      run: docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/hddm:latest -f Dockerfile . --push
